jackett:
  base_url: "http://192.168.1.117:9117"
  api_key: "i8d29p3srwerdcgep8px29oki91rw5i7"

qbittorrent:
  base_url: "http://192.168.1.117:8080"
  username: "admin"
  password: "nascar11"

downloads:
  directory: "/opt/rompi/downloads"
