jackett:
  base_url: "http://192.168.1.108:9117"
  api_key: "3xlyftv440ixgpbta5kpqmzfp6pkrmd5"

qbittorrent:
  base_url: "http://192.168.1.117:8080"
  username: "admin"
  password: "nascar11"

downloads:
  directory: "/opt/rompi/downloads"

aria2:
  rpc_url: "http://localhost:6800/jsonrpc"
  rpc_secret: "rompi_aria2_secret_2024"
